version: "3.9"
services:
  #backend:
  #  ports:
  #  - 8080:8080
  postgres:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: passme
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
    - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer:4.8.0
    restart: always
    ports:
      - 8090:8080
  #keycloak:
