= Tutorial: Quarkus App with Docker
Thomas W. Stütz
2.0.0, 2023-04-29: How to use quarkus & docker @ HTL Leonding college
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:toclevels: 5
:experimental: true
:linkattrs:   // so window="_blank" will be executed

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/quarkus-docker-gh-actions-demo/master/asciidocs/index.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/quarkus-docker-gh-actions-demo] ‏ ‏ ‎
icon:home[link=https://htl-leonding-college.github.io/quarkus-docker-gh-actions-demo/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Create a Quarkus Application

=== Create the Project

* Configure on https://code.quarkus.io/?g=ast.htlleonding.vehicle&a=vehicle-demo&e=resteasy-reactive&e=resteasy-reactive-jackson&e=smallrye-openapi&e=jdbc-postgresql&e=hibernate-orm-panache&extension-search=origin:platform%20panache[quarkus.io^] and download as zip or push to github

* Alternatively create the project per maven

** Check the newest quarkus version https://quarkus.io/

[source,bash]
----
mvn io.quarkus.platform:quarkus-maven-plugin:3.0.1.Final:create \
    -DprojectGroupId=at.htlleonding.vehicle \
    -DprojectArtifactId=vehicle-demo \
    -Dextensions="resteasy-reactive, resteasy-reactive-jackson, smallrye-openapi, jdbc-postgresql, hibernate-orm-panache"
----

=== First Run of the Project

.open a terminal
[source,bash]
----
./mvnw clean compile quarkus:dev
----

=== Manually Check of the Running Project

.open another terminal
[source,bash]
----
curl http://localhost:8080/vehicle
----

.output
----
Hello RESTEasy
----

=== Build a jar-File

.build a jar-file (package)
----
./mvnw clean package
----

.result -> ls -lh ./target
----
-rw-r--r--   1 stuetz  staff   5.4K Mar 14 12:08 quarkus-docker-gh-actions-demo-0.1.0-SNAPSHOT.jar
----

* the name of the jar-file is not a telling name
* -> we will rename the jar-file

=== Rename the jar-File

.rename the project into vehicle w/ version#
[source,xml]
----
//...
<build>
  <finalName>vehicle-${version}</finalName>
  <plugins>
    //...
  </plugins>
</build>
----

* There is also a property https://quarkus.io/guides/all-config#quarkus-core_quarkus.package.output-name[quarkus.package.output-name^]


.build a jar-file (package)
----
./mvnw clean package
----

It produces the `quarkus-run.jar` file in the `target/quarkus-app/` directory.
Be aware that it’s not an _uber-jar_ as the dependencies are copied into the `target/quarkus-app/lib/` directory.

----
ls -l target
----

.result
----
-rw-r--r--  1 stuetz  staff  180323 Apr 29 11:56 vehicle-1.0.0-SNAPSHOT.jar
----

.run the app
----
java -jar target/vehicle-1.0.0-SNAPSHOT.jar
----

.result
----
no main manifest attribute, in target/vehicle-1.0.0-SNAPSHOT.jar
----

.but there is also
----
tree target/quarkus-app

target/quarkus-app
|-- app
|   `-- vehicle-0.1.0-SNAPSHOT.jar
|-- lib
|   |-- boot
|   |   |-- io.quarkus.quarkus-bootstrap-runner-3.0.1.Final.jar
|   |   |-- ...
|   `-- main
|       |-- com.fasterxml.jackson.core.jackson-annotations-2.14.2.jar
|       |-- ...
├── quarkus
│   ├── generated-bytecode.jar
│   ├── quarkus-application.dat
│   └── transformed-bytecode.jar
├── quarkus-app-dependencies.txt
└── quarkus-run.jar
----

.run the app
----
java -jar target/quarkus-app/quarkus-run.jar
----

* the libraries are in the lib-folder available

=== Choose a Packaging Format

* there are several aspects to pay attention:
** fast-jar or legacy-jar [https://www.heise.de/news/Java-Framework-Quarkus-1-12-erhebt-Fast-jar-zum-Standard-5064039.html[heise, window="_blank"]]
** create a uber-jar or deliver the quarkus-app-folder


* What is a uber-jar?
** Über is the German word for above or over (it's actually cognate with the English over).
Hence, in this context, an uber-jar is an "over-jar", one level up from a simple JAR (a), defined as one that contains both your package and all its dependencies in one single JAR file. The name can be thought to come from the same stable as ultrageek, superman, hyperspace, and metadata, which all have similar meanings of "beyond the normal".
** uber-jar is also known as fat jar i.e. jar with dependencies.
There are three common methods for constructing an uber jar (https://stackoverflow.com/a/39030649[stackoverflow, window="_blank"]):
. *Unshaded*: Unpack all JAR files, then repack them into a single JAR. Works with Java's default class loader. Tools *maven-assembly-plugin*
. *Shaded*: Same as unshaded, but rename (i.e., "shade") all packages of all dependencies. Works with Java's default class loader. Avoids some (not all) dependency version clashes. Tools *maven-shade-plugin*
. *JAR of JARs*: The final JAR file contains the other JAR files embedded within. Avoids dependency version clashes. All resource files are preserved. Tools: *Eclipse JAR File Exporter*

==== How to change the package type?

* You have to change the https://quarkus.io/guides/all-config#quarkus-core_quarkus.package.type[quarkus.package.type]-property
* options:
** jar -> fast-jar
** legacy-jar
** uber-jar
** native
* Where can you change the property?
** application.properties
+
----
quarkus.package.type=uber-jar
----
** pom.xml
+
[source,xml]
----
<properties>
  <quarkus.package.type>uber-jar</quarkus.package.type>
</properties>
----
** as maven-parameter
+
----
./mvnw clean package -Dquarkus.package.type=uber-jar
----

.result
----
-rw-r--r--   1 stuetz  staff    14M Mar 14 12:35 vehicle-0.1.0-SNAPSHOT-runner.jar #<.>
-rw-r--r--   1 stuetz  staff   5.4K Mar 14 12:35 vehicle-0.1.0-SNAPSHOT.jar.original
----

<.> the -runner - file includes all necessary libraries for running the quarkus app


=== Run the jar-File

----
java -jar ./target/vehicle-0.1.0-SNAPSHOT-runner.jar
----

=== Check the Running App manually

----
curl http://localhost:8080/vehicle
----

.result
----
Hello RESTEasy
----

== Run in Docker

[source,bash]
----
./mvnw clean package
----

[source,sh]
----
docker build -f src/main/docker/Dockerfile.jvm -t htl-leonding/vehicle .
----

https://catalog.redhat.com/software/containers/search?p=1&q=ubi[Red Hat container images, window="_blank"]

[source,shell]
----
docker run -i --rm -p 8080:8080 htl-leonding/vehicle
----

== Run in docker-compose

* Maybe you will download all docker-images
** docker pull adminer:4.8.0
** docker pull postgres:13.2

* Sources:
** https://docs.docker.com/compose/compose-file/compose-versioning/[docker-compose versions]
** https://github.com/docker/awesome-compose[awesome-compose, a curated list of docker-compose examples, window="_blank"]
** https://github.com/lreimer/hands-on-quarkus/blob/master/docker-compose.yml
** http://heidloff.net/article/multistage-dockerfiles-for-quarkus/[Multistage Dockerfiles for Quarkus, window="_blank"]



== Create a github-actions Pipeline


