= Tutorial: Quarkus App with Docker
Thomas W. Stütz
1.0.0, 2021-03-14: How to use ssh in project work @ HTL Leonding college
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
:toclevels: 5
:experimental: true
:linkattrs:   // so window="_blank" will be executed

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:file-text-o[link=https://raw.githubusercontent.com/htl-leonding-college/security-lecture-notes/master/asciidocs/{docname}.adoc] ‏ ‏ ‎
icon:github-square[link=https://github.com/htl-leonding-college/security-lecture-notes] ‏ ‏ ‎
icon:home[link=http://edufs.edu.htl-leonding.ac.at/~t.stuetz/hugo/]
endif::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

== Erstellen der Quarkus Application

=== Generieren des Projekts

* Vorab unter https://quarkus.io/ die neueste Quarkus-Version abrufen und ggf. unten eintragen

[source,bash]
----
mvn io.quarkus:quarkus-maven-plugin:1.12.2.Final:create -e \
    -DprojectGroupId=at.htl.vehicle \
    -DprojectArtifactId=quarkus-docker-gh-actions-demo \
    -DclassName="at.htl.vehicle.boundary.VehicleEndpoint" \
    -Dpath="/vehicle" \
    -Dextensions="resteasy, resteasy-jsonb, smallrye-openapi"
----

=== Starten des Projects

.Terminal öffnen
[source,bash]
----
./mvnw clean compile quarkus:dev
----

=== Testen des Projects

.Neues Terminal öffnen
[source,bash]
----
curl http://localhost:8080/vehicle
----

.output
----
Hello RESTEasy
----

=== Build des Projects

.build a fast-jar
----
./mvnw clean package
----


[source,xml]
----
...
<build>
  <finalName>vehicle-${version}</finalName>
  <plugins>
    ...
----


* What is a uber-jar?
** Über is the German word for above or over (it's actually cognate with the English over).
Hence, in this context, an uber-jar is an "over-jar", one level up from a simple JAR (a), defined as one that contains both your package and all its dependencies in one single JAR file. The name can be thought to come from the same stable as ultrageek, superman, hyperspace, and metadata, which all have similar meanings of "beyond the normal".
** uber-jar is also known as fat jar i.e. jar with dependencies.
There are three common methods for constructing an uber jar (https://stackoverflow.com/a/39030649[stackoverflow, window="_blank"]):
. *Unshaded*: Unpack all JAR files, then repack them into a single JAR. Works with Java's default class loader. Tools maven-assembly-plugin
. *Shaded*: Same as unshaded, but rename (i.e., "shade") all packages of all dependencies. Works with Java's default class loader. Avoids some (not all) dependency version clashes. Tools maven-shade-plugin
. *JAR of JARs*: The final JAR file contains the other JAR files embedded within. Avoids dependency version clashes. All resource files are preserved. Tools: Eclipse JAR File Exporter
