## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PROJECT_NAME: vehicle
  PROJECT_VERSION: latest
  ORG_ACTOR: htl-lleonding-college

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Debug
        run: |
          echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
          echo ${{ env.REGISTRY }}
          echo ${{ env.org_actor }}
          echo ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.PROJECT_NAME }}
          echo +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.org_actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          ./mvnw package -DskipTests -B
          docker push ${{ env.REGISTRY }}/${{ env.org_actor }}/${{ env.PROJECT_NAME }}:${{ env.PROJECT_VERSION }}


